#!/bin/sh
# On a $1 = le dossier de télechargement
#  J'ai rajouté des options pour qu'on ait plus de libertes
#Comportement de base du programme
musique_file=./

#Options
while getopts "f" option
do
	case $option in
		#On choisit ou on extrait la musique
		f)musique_file=$2
		shift;;
		#Autre chose que l'option f
		?)echo "usage: option inconnue"
		exit 1;;
	esac
done
 
#Liste tous les fichiers musicaux dans le dossier de telechargement
musique=`ls $1 | grep -P ".*- Jamendo - MP3.zip" >/tmp/musique.$$`
 
#On va extraire les archives une a une
while read line
do
    #On va affacer ce qu'il a en trop et on va creer le dossier
    namedir=`echo $line | cut -d'-' -f1,2`
	
	#On extrait l'archive sans afficher et sans remplacer les fichiers exitants
	unzip -qn $1/"$line" -d $rmusique_file/"$namedir"
 
done < /tmp/musique.$$
 
#Je supprime mon fichier temp
rm -f /tmp/musique.$$
